### ISSUE TITLE
Electrs Liquid with custom fedpegscript panics

### ISSUE THREAD

**Issue by tiero** [Blockstream/esplora#330]
I am running electrs-liquid in `liquidregtest` network and if I change the fedpegscript to something different than `OP_TRUE` electrs it panics

```
thread 'lookup-txo-14' panicked at 'missing txo [elements]f85afc42db7074938eb7078f7a534ce66f4dc1966ab9a818c9d492dc5a3cbab2:0 in DB { db: RocksDB { path: "./db/liquidregtest/newindex/txstore" } }', src/new_index/schema.rs:1042:29
```

This my `elements.conf`

```
chain=liquidregtest
listen=1
txindex=1

[liquidregtest]
port=18886
rpcport=18884
rpcuser=admin1
rpcpassword=123
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

mainchainrpcport=18443
mainchainrpcuser=admin1
mainchainrpcpassword=123

fedpegscript=512102e260747129f9bf037ceefaa84603e0c46cb247f0b860b36acdb7f26d8407971f0269e0180bc9e0be7648d6e9c17f3664bc3ebcee40f3a46cf4b42e583e96b911b951ae

validatepegin=0
initialfreecoins=2100000000000000
fallbackfee=0.000001

```

This how I run `electrs` for liquid

```yml
electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30001
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - 50001:50001
      - 30001:30001
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped
```

Complete stacktrace can be found here 
https://paste.centos.org/view/6751d2d5
