### ISSUE TITLE
docker-compose setup example?

### ISSUE THREAD

**Issue by GopherJ** [Blockstream/esplora#491]
```
version: '3.7'
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    ports:
      - 18443:18443
      - 30001:30001
    command:
      - "-daemon=0"
      - "-debug=1"
      - "-debugexclude=libevent"
      - "-debugexclude=leveldb"
      - "-regtest=1"
      - "-rpcbind=0.0.0.0:18443"
      - "-rpcuser=devnet"
      - "-rpcpassword=devnet"
      - "-rpcallowip=0.0.0.0/0"
      - "-server=1"
      - "-txindex=1"
      - "-prune=0"
      - "-fallbackfee=0.0001"
      - "-zmqpubhashtx=tcp://0.0.0.0:30001"
      - "-zmqpubhashblock=tcp://0.0.0.0:30001"
      - "-zmqpubrawblock=tcp://0.0.0.0:30002"
      - "-zmqpubrawtx=tcp://0.0.0.0:30002"
    volumes:
      - "./chaindata/bitcoind:/home/bitcoin/.bitcoin"
    networks:
      testing_net:
        ipv4_address: 172.16.238.11
    restart: always

  electrs:
    image: blockstream/esplora:electrs-latest
    ports:
      - 3000:3000
      - 50001:50001
    user: root
    command:
      - "/app/electrs_bitcoin/bin/electrs"
      - "-vvvv"
      - "--timestamp"
      - "--daemon-dir=/app/.bitcoin"
      - "--db-dir=/app/db"
      - "--network=regtest"
      - "--http-addr=0.0.0.0:3000"
      - "--electrum-rpc-addr=0.0.0.0:50001"
      - "--daemon-rpc-addr=172.16.238.11:18443"
      - "--cookie=devnet:devnet"
      - "--electrum-txs-limit=1000000"
      - "--cors=*"
      - "--utxos-limit=1000000"
    volumes:
      - "./chaindata/explorer:/app/db"
      - "./chaindata/bitcoind:/app/.bitcoin"
    networks:
      testing_net:
        ipv4_address: 172.16.238.12
    restart: always

  esplora:
    image: blockstream/esplora:latest
    network_mode: "host"
    environment:
      - API_URL=http://devnet:devnet@localhost:3000
    command:
      - "/srv/explorer/run.sh"
      - "bitcoin-regtest"
      - "explorer"
    volumes:
      - "./chaindata/bitcoind:/data"
    restart: always

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```
