### ISSUE TITLE
Bitcoin core docker compose + esplora

### ISSUE THREAD

**Issue by thewrlck** [Blockstream/esplora#541]
Hi, I would like to connect esplora to my bitcoin core node.

This is my actual docker compose but don't work:

```
services:
    bitcoin_signet:
      container_name: bitcoin_signet
      image: bitcoin/bitcoin:latest
      stop_grace_period: 1m
      command:
        - -printtoconsole=1
        - -signet=1
        - -server=1
        - -txindex=1
        - -rpcallowip=172.0.0.0/8
        - -rpcbind=0.0.0.0
        - -rpcauth=${RPCAUTH}
      ports:
        - 38332:38332
        - 38333:38333
      volumes:
        - ./bitcoin:/home/bitcoin/.bitcoin
      networks:
        - bitcoin_signet_network
    esplora_signet:
      container_name: esplora_signet
      image: blockstream/esplora:latest
      build:
        context: ./esplora
        dockerfile: Dockerfile
      stop_grace_period: 1m
      command: /srv/explorer/run.sh bitcoin-signet explorer
      ports:
        - 8084:80
        - 50001:50001
      volumes:
        - ./esplora_data:/data
      environment:
        ELECTRS_ARGS: --utxos-limit 1000000 --jsonrpc-import  --cors '*' --daemon-rpc-addr bitcoin_signet:38332
      networks:
        - bitcoin_signet_network

networks:
  bitcoin_signet_network:
    name: bitcoin_signet_network
```
